#:import HomeScreen src.screens.homescreen.HomeScreen
#:import RomaneiosScreen src.screens.romaneiosscreen.RomaneiosScreen
#:import CreateRomaneioScreen src.screens.createromaneioscreen.CreateRomaneioScreen
#:import DetailsRomaneioScreen src.screens.detailsromaneioscreen.DetailsRomaneioScreen

<MainScreenManager>:
    HomeScreen:
    RomaneiosScreen:
    CreateRomaneioScreen:
    DetailsRomaneioScreen: